### ISSUE TITLE
关于使用的问题

### ISSUE THREAD

**Issue by tjcchen** [dengpan20/speedss#1]
Hi 您好：

speedss的梯子好用么，具体咱们这个代码仓库该如何使用生成账号呢？我简单试了一下speedss的注册，说是需要邀请人邮箱，被卡在那里了。所以想和您问下相关信息，非常感谢哈！

感谢，
陈阳

**Comment by dengpan20** [comment]
> Hi 您好：
> 
> speedss的梯子好用么，具体咱们这个代码仓库该如何使用生成账号呢？我简单试了一下speedss的注册，说是需要邀请人邮箱，被卡在那里了。所以想和您问下相关信息，非常感谢哈！
> 
> 感谢，
> 陈阳
好用，邀请码，可以用我的邮箱进行邀请  ：dengpan616@qq.com，
本人已经用过几年了，没出现过什么大的问题。

**Comment by tjcchen** [comment]
ok, 收到！非常感谢您的回复~
